#
# filename: docker-compose.yaml
# description: -
##

version: "2"
services:

    ###########################
    # External containers     #
    ###########################

    # nginx reverse proxy
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: nginx.Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /var/www/html:/var/www/html
        links:
            - shadowform.dev
            - powerhousemgmt

    # certbot for auto ssl renewal
    certbot:
        image: certbot/certbot

    ###########################
    # Website containers      #
    ###########################

    # https://shadowform.dev
    shadowform.dev:
        container_name: shadowform.dev 
        build:
            args:
             - GIT_REPO=git@github.com:zyarash/shadowform.dev.git
            context: .
            dockerfile: nodejs.Dockerfile
        expose:
            - "3000"

    # https://powerhousemgmt.com
    powerhousemgmt:
        container_name: powerhousemgmt
        build:
            args:
             - GIT_REPO=git@github.com:zyshara/powerhousemgmt.git
            context: .
            dockerfile: webpack.Dockerfile
        expose:
            - "3000"

networks:
    default:
        external:
            name: language
